name: video_player_hdr
description: A fork of video_player with HDR support
repository: https://github.com/rubengmlp/video_player_hdr
issue_tracker: https://github.com/rubengmlp/video_player_hdr/issues
version: 1.0.0

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.rubengmlp.video_player_hdr
        pluginClass: VideoPlayerHdrPlugin
      ios:
        pluginClass: VideoPlayerHdrPlugin
      macos:
        default_package: video_player_avfoundation
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
<<<<<<< HEAD
  video_player_avfoundation: ^2.5.6
  video_player_platform_interface: ^6.2.0
  video_player_android: 2.8.1
=======
  video_player_platform_interface: ^6.2.0
  video_player_avfoundation: ^2.5.6
  video_player_android: ^2.8.3
>>>>>>> implement-ios-plugin
  video_player_web: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leak_tracker_flutter_testing: any

topics:
  - video
  - video-player
